### ISSUE TITLE
Goes offline after some time

### ISSUE THREAD

**Issue by tnemrap** [nibi79/synologysurveillancestation#18]
Diskstation item goes offline after some time and flood error log.
`2018-01-03 21:48:40.014 [ERROR] [n.internal.thread.SynoApiThreadEvent] - could not get event org.eclipse.smarthome.core.thing.internal.ThingImpl@664a3917: {}
java.lang.NullPointerException: null
        at org.openhab.binding.synologysurveillancestation.internal.webapi.SynoWebApiHandler.getEventResponse(SynoWebApiHandler.java:459) [196:org.openhab.binding.synologysurveillancestation:2.2.0.a16]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThreadEvent.refresh(SynoApiThreadEvent.java:51) [196:org.openhab.binding.synologysurveillancestation:2.2.0.a16]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread$1.run(SynoApiThread.java:51) [196:org.openhab.binding.synologysurveillancestation:2.2.0.a16]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
`

/Mike

**Comment by Pavion** [comment]
You still seem to have a16. Please upgrade to a17 (simply download and copy over), this problem should be hopefully fixed.

**Comment by tnemrap** [comment]
Seems to be fixed in a17.

/Mike
