### ISSUE TITLE
Thread HomeMode: Critical error

### ISSUE THREAD

**Issue by tnemrap** [nibi79/synologysurveillancestation#22]
When i link an item to home mode i receive this error.

`2018-01-15 14:21:03.270 [ERROR] [tation.internal.thread.SynoApiThread] - Thread HomeMode: Critical error:
 {}
java.lang.NullPointerException: null
        at org.openhab.binding.synologysurveillancestation.internal.webapi.SynoWebApiHandler.getHomeModeResponse(SynoWebApiHandler.java:471) [260:org.openhab.binding.synologysurveillancestation:2.2.0.a20]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThreadHomeMode.refresh(SynoApiThreadHomeMode.java:39) [260:org.openhab.binding.synologysurveillancestation:2.2.0.a20]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread.runOnce(SynoApiThread.java:131) [260:org.openhab.binding.synologysurveillancestation:2.2.0.a20]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread$1.run(SynoApiThread.java:61) [260:org.openhab.binding.synologysurveillancestation:2.2.0.a20]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]`

**Comment by Pavion** [comment]
Have you recreated your Bridge Thing?
Was it an one time error or a repeating error?
What is the behavior upon restart?

**Comment by tnemrap** [comment]
Bridge Thing recreated
Repeating error
Same after restart but it take some time before reappearing.

**Comment by Pavion** [comment]
I've forgotten an exception handling there. With next release you should see an error: "Handler gone offline" instead. This error is normal at startup only and happens if a Thing refresh is requested prior to connection being established. This should **not** happen later and should **not** affect general home mode functionality. I'll check on this issue again after the next release. Thanks for keeping me posted!

**Comment by Pavion** [comment]
Should be corrected now, please reopen if still relevant.
