### ISSUE TITLE
Binding won't reconnect on Disk Station restart

### ISSUE THREAD

**Issue by b-r-y** [nibi79/synologysurveillancestation#34]
Hi guys,

If you remember from the openhab forum i have older Synology NAS with a rather old API version and cannot upgrade. Pavion was able to fix the authentication issue and from what i can read in the docs it should also be simple to fix for the live streaming.

I get the following two errors when trying to define an item on the live streaming channels:

> 2019-01-31 19:06:41.765 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.openhab.binding.synologysurveillancestation.internal.webapi.response.LiveUriResponse.getMjpegHttp(LiveUriResponse.java:52) ~[?:?]
	at org.openhab.binding.synologysurveillancestation.handler.SynoCameraHandler.handleCommand(SynoCameraHandler.java:150) ~[?:?]
	at org.openhab.binding.synologysurveillancestation.handler.SynoCameraHandler.channelLinked(SynoCameraHandler.java:255) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:300) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-01-31 19:07:10.659 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'security.items'
2019-01-31 19:07:10.774 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.openhab.binding.synologysurveillancestation.internal.webapi.response.LiveUriResponse.getRtsp(LiveUriResponse.java:38) ~[?:?]
	at org.openhab.binding.synologysurveillancestation.handler.SynoCameraHandler.handleCommand(SynoCameraHandler.java:144) ~[?:?]
	at org.openhab.binding.synologysurveillancestation.handler.SynoCameraHandler.channelLinked(SynoCameraHandler.java:255) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:300) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

I tracked the method you use in v2.8 to be `GetLiveViewPath `. Yet this was introduced in v2.6 as a rename of `GetStmUrlPath `. `GetStmUrlPath ` itself was only introduced in v2.4.

I myself am not sure which API my SS v7.1 has - i can only deduce from some release notes and it's mostly a guess... Anyway i think it is v2.0. For v2.0 of the API i think corresponding method is Stream (page 208) of --> [this](https://global.download.synology.com/download/Document/DeveloperGuide/Surveillance_Station_Web_API_v2.0.pdf) <--- document.

I don't know java very much and i was hoping you can help me make it work. For what is worth i think the fix will be common for both mjpeg and rtsp.

Thanks!

Cheers
Boyan

**Comment by Pavion** [comment]
Hi there! 

Just think around the corner... :) 

If your __static snapshot__ is working, you can obtain the live URI using JS transformation, as stated in readme:
https://github.com/nibi79/synologysurveillancestation/tree/master#transformation

In your case the js function would look like:
```
(function(i) {
    return i.replace("SYNO.SurveillanceStation.Camera", "SYNO.SurveillanceStation.Stream.VideoStreaming").replace("version=8", "version=1").replace("GetSnapshot", "Stream&format=mjpeg")
})(input)
```

**Comment by Pavion** [comment]
I've added more info in the corresponding section of the readme. Your feedback would be appreciated.

**Comment by b-r-y** [comment]
Hi @Pavion ,

I noticed the Bridge+thing defined in a .thing file are not recognized after reboot of the synology. Have you seen this before? There are no errors in the log but PaperUI says Home Mode error after reboot. To fix i had to remove the definitions from the .thing file and reboot openhab and then add them again. If you think it's worth i can reproduce this and may be send boot logs?

now back to the transform topic --> it works!

There is only one minor bug on my end - the VideoStreaming is a top level API and not subset to Streaming so it looks like this:

`
(function (i) {
    return i.replace("SYNO.SurveillanceStation.Camera", "SYNO.SurveillanceStation.VideoStreaming").replace("version=8", "version=1").replace("GetSnapshot", "Stream&format=mjpeg")
})(input)
`

Cheers,
Boyan

**Comment by b-r-y** [comment]
perhaps one more note - on the sitemap one should use Image. --> ok this was wrong!

Video work as well and only the video part shows up on the android app.

**Comment by Pavion** [comment]
I'm glad you've got it working with the transformation! 

As for your reboot issue: I must admit I don't know if I've ever tested it. 
My openHAB is running on DiskStation so if I'm to reboot it, I have to shutdown openHAB first. 
I'll take a look at this.

**Comment by Pavion** [comment]
Five days later... 
There was actually no reconnect at all. I had to rework tons of code to get it going. Now there should be only one SID (which is now accessible in a separate Bridge Channel). Upon reconnect new SID will be requested, threads and channels updated. Fixed many other small issues regarding disconnects, station restarts and configuration updates. 
_Running an overnight test, aiming to make a release tomorrow_

**Comment by bry-gomspace** [comment]
great! I could have helped  - i did not realize you were going through all this. I'll test the release once you have it out, or before if you prefer?

**Comment by Pavion** [comment]
Thank you for your offer but it was a pure chaos to begin with so I've spend most of my time wondering why I've done such things in first place :)
You are welcome to test the newest version, released just now.

**Comment by b-r-y** [comment]
So i finally got around to try this and it works. Simply replaced the JAR in add ons and rebooted the synology. Worked out of the box - good job!

**Comment by Pavion** [comment]
Thanks for reporting back, feel free to create new issues, if necessary.
