### ISSUE TITLE
NullPointerException when disconnected from network

### ISSUE THREAD

**Issue by jlaur** [nibi79/synologysurveillancestation#52]
Detected in logs after unplugging network cable to openHAB server for some unrelated testing:
```
2022-04-01 15:20:23.153 [ERROR] [tation.internal.thread.SynoApiThread] - DeviceId: Bridge; Thread: Snapshot; Critical error:

java.lang.NullPointerException: null
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThreadSnapshot.refresh(SynoApiThreadSnapshot.java:50) ~[bundleFile:?]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread.runOnce(SynoApiThread.java:135) [bundleFile:?]
        at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread$1.run(SynoApiThread.java:67) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Pavion** [comment]
Closing issue with the official Marketplace release. NPE or the mentioned error may occur once upon binding update or on configuration change, which issue might be addressed later.
